# See the documentation for more information:
# https://packit.dev/docs/configuration/

---
upstream_tag_template: v{version}
jobs:
  - <<: &pr_build
      job: copr_build
      trigger: pull_request
      targets:
        - fedora-all-x86_64
        - fedora-all-aarch64

  - <<: *pr_build
    trigger: commit
    preserve_project: true
