FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi8/go-toolset:1.19 AS develop
RUN dnf install -y nodejs

FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi8/go-toolset:1.19 AS build
RUN go build

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8 as runtime
RUN microdnf install gcc
