name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [39, 40, rawhide]

    steps:
    - name: Set up podman
      run: |
        sudo apt update
        sudo apt-get -y install podman
        podman pull registry.fedoraproject.org/fedora:${{ matrix.fedora-version }}
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/rpm-lockfile-prototype
        flavor: |
          latest=true
    - uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: .
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Test with pytest
      run: |
        {
          echo 'FROM registry.fedoraproject.org/fedora:${{ matrix.fedora-version }}'
          echo 'RUN dnf install -y python3-pip python3-dnf'
          echo 'WORKDIR /src'
          echo 'RUN python3 -m pip install . pytest'
          echo 'RUN pytest -v'
        } > podmanfile
        podman build -v $(pwd):/src --tag test -f ./podmanfile

